language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-23
    - extra-android-m2repository

before_script:
    - chmod +x gradlew

script: "./gradlew build"
